#!/bin/bash

echo "Enter the 1st number : "
read num1

echo "Enter the 2nd number : "
read num2

echo "Enter the 3rd number : "
read num3

if (($num1 > $num2  &&  $num1 > $num3))
then
echo "$num1 is the greatest"
elif (($num2 > $num1  && $num2 > $num3))
then
echo "$num2 is the greatest"
else
echo "$num3 is the greatest"
fi
